"""
EquationAI — Export Service
Generates downloadable LaTeX, MathML, and PDF files.
"""

import io
from app.core.logging_config import get_logger

logger = get_logger("export_service")


def export_latex(latex: str, title: str = "Equation") -> bytes:
    """Generate a .tex file content."""
    content = f"""% EquationAI — Exported LaTeX Document
% Title: {title}
% Generated by EquationAI

\\documentclass[12pt]{{article}}
\\usepackage{{amsmath, amssymb, amsfonts}}
\\usepackage[utf8]{{inputenc}}

\\title{{{title}}}
\\date{{\\today}}

\\begin{{document}}
\\maketitle

\\section*{{Equation}}

\\begin{{equation}}
{latex}
\\end{{equation}}

\\end{{document}}
"""
    return content.encode("utf-8")


def export_mathml(mathml: str, title: str = "Equation") -> bytes:
    """Generate a .mml file content."""
    content = f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- EquationAI — Exported MathML Document -->
<!-- Title: {title} -->
{mathml}
"""
    return content.encode("utf-8")


def export_pdf(latex: str, mathml: str = "", title: str = "Equation Report") -> bytes:
    """Generate a PDF report with equation details."""
    try:
        from fpdf import FPDF

        pdf = FPDF()
        pdf.add_page()
        page_width = pdf.w

        # Header
        pdf.set_fill_color(0, 102, 204)
        pdf.rect(0, 0, page_width, 35, 'F')
        pdf.set_text_color(255, 255, 255)
        pdf.set_font('Helvetica', 'B', 20)
        pdf.set_y(10)
        pdf.cell(0, 15, 'EquationAI Report', align='C', new_x="LMARGIN", new_y="NEXT")

        pdf.set_y(45)

        # Title
        pdf.set_text_color(11, 29, 51)
        pdf.set_font('Helvetica', 'B', 16)
        pdf.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)

        # LaTeX Section
        pdf.set_font('Helvetica', 'B', 13)
        pdf.set_text_color(11, 29, 51)
        pdf.cell(0, 8, '1. LaTeX Source Code', new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

        pdf.set_font('Courier', '', 10)
        pdf.set_text_color(51, 65, 85)
        pdf.set_fill_color(248, 250, 252)
        pdf.set_draw_color(226, 232, 240)

        split_latex = pdf.multi_cell(
            w=page_width - 40,
            h=5,
            text=latex,
            border=1,
            fill=True,
            new_x="LMARGIN",
            new_y="NEXT",
            output="LINES" if hasattr(pdf, '_putpages') else None,
        )
        pdf.ln(8)

        # MathML Section
        if mathml:
            pdf.set_font('Helvetica', 'B', 13)
            pdf.set_text_color(11, 29, 51)
            pdf.cell(0, 8, '2. MathML Markup', new_x="LMARGIN", new_y="NEXT")
            pdf.ln(3)

            pdf.set_font('Courier', '', 8)
            pdf.set_text_color(51, 65, 85)
            pdf.multi_cell(
                w=page_width - 40,
                h=4,
                text=mathml[:2000],  # Truncate very long MathML
                border=1,
                fill=True,
                new_x="LMARGIN",
                new_y="NEXT",
            )

        # Footer
        pdf.set_y(-20)
        pdf.set_font('Helvetica', 'I', 8)
        pdf.set_text_color(148, 163, 184)
        pdf.cell(0, 10, 'Generated by EquationAI — AI-Powered Mathematical Processing Platform', align='C')

        return pdf.output()

    except ImportError:
        logger.warning("fpdf2 not installed — generating text-only PDF fallback")
        # Fallback: return a plain text representation
        content = f"EquationAI Report\n{'=' * 40}\n\nLaTeX:\n{latex}\n"
        if mathml:
            content += f"\nMathML:\n{mathml}\n"
        return content.encode("utf-8")
